name       : akonadi-calendar
version    : 22.12.1
release    : 67
source     :
    - https://cdn.download.kde.org/stable/release-service/22.12.1/src/akonadi-calendar-22.12.1.tar.xz : 2f0890942830527385c469e7e52f3818e761e05e2768a7606597b8ea7614f31e
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kwallet-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
