name       : akonadi-calendar
version    : 20.12.3
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.3/src/akonadi-calendar-20.12.3.tar.xz : 93275e67e403056a5d7ba9c4231a10ec08e2df542525378d507d37e493f8f114
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - kpimtextedit-devel
    - kwallet-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
