name       : akonadi-calendar
version    : 21.12.3
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.3/src/akonadi-calendar-21.12.3.tar.xz : 78617cb53b3e9a4abdae34db63e57fb884ad412428fb722f9806a87e9337fe43
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - kpimtextedit-devel
    - kwallet-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
