name       : akonadi-calendar
version    : 22.04.1
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/akonadi-calendar-22.04.1.tar.xz : 359c86f9fe84ea0b66629f143244dda0c14b534e34feacf88971f5170ba111cb
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - knotifications-devel
    - kpimtextedit-devel
    - kwallet-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
