name       : akonadi-calendar
version    : 21.12.0
release    : 59
source     :
    - https://cdn.download.kde.org/stable/release-service/21.12.0/src/akonadi-calendar-21.12.0.tar.xz : 7a5df066f330b1dfdd290c579132f7e84d3f8cea941da4b2f6830b170ec07f4a
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - akonadi-contacts-devel
    - akonadi-mime-devel
    - kcalendarcore-devel
    - kcalutils-devel
    - kcontacts-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - kpimtextedit-devel
    - kwallet-devel
rundeps    :
    - devel :
        - akonadi-devel
        - kcalendarcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
