name       : akonadi-calendar
version    : 19.12.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/akonadi-calendar-19.12.0.tar.xz : 84671189a5ad87259f15c54f673954f7496a6043a3efedaf2e2376b0af5ff6d5
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
