name       : akonadi-calendar
version    : 20.08.0
release    : 42
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.0/src/akonadi-calendar-20.08.0.tar.xz : 4664e2dc6bc0762d999662188c64410fa70be2cef1be221569ec3b9270f80fd8
homepage   : https://kde.org/
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalutils-devel
    - kcontacts-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - kwindowsystem-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
