name       : akonadi-calendar
version    : 18.08.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.1/src/akonadi-calendar-18.08.1.tar.xz : 9ad5b90f156d811ccd689b579376652988d946be61e01bac7223581c34cadcce
license    : LGPL-2.1
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
