name       : akonadi-calendar
version    : 19.04.3
release    : 24
source     :
    - https://cdn.download.kde.org/stable/applications/19.04.3/src/akonadi-calendar-19.04.3.tar.xz : 939691e3c31993e3708a74759cbab951a51d0b36239426fe09c9ee9ff9622013
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdbusaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kidentitymanagement-devel
    - kio-devel
    - kitemmodels-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
