name       : akonadi-calendar
version    : 17.08.3
release    : 4
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/akonadi-calendar-17.08.3.tar.xz : 662143b9ac75efae3a244d9a18069466ed2b458073896d778a8443308f5024f0
license    : LGPL-2.1
component  : desktop.library
summary    : Library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library
description: |
    Akonadi Calendar is a library that effectively bridges the type-agnostic API of the Akonadi client libraries and the domain-specific KCalCore library. It provides jobs, models and other helpers to make working with events and calendars through Akonadi easier.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libsasl2)
    - pkgconfig(Qt5Core)
    - akonadi-contacts-devel
    - akonadi-devel
    - akonadi-mime-devel
    - extra-cmake-modules
    - kcalcore-devel
    - kcalutils-devel
    - kcodecs-devel
    - kcontacts-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kidentitymanagement-devel
    - kio-devel
    - kmailtransport-devel
    - kmime-devel
    - kpimtextedit-devel
    - kwallet-devel
    - libboost-devel
    - libical-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
